/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Renafox (https://sketchfab.com/kryik1023)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/models/544aa41de67b48cf89f8fcc2bb06e8f4
title: Old Rusty Car 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car1(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car-draco-1.glb')
  console.log(nodes);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Object001_Material_#37_0'].geometry} material={materials.Material_37} material-color={"red"} scale={[0.5,0.5,0.5]}/>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Object002_Material_#33_0'].geometry} material={materials.Material_33} material-color={"black"}  scale={[0.5,0.5,0.5]}/>
          </group>
          <group position={[0.82, 1.86, -1.26]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Plane001_Material_#58_0'].geometry} material={materials.Material_58}  scale={[0.5,0.5,0.5]}/>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car-draco-1.glb')
